Convert to using GNU autotest tool
The testsuite support in automake is very limited and inadequate for purpose.
The GNU autotest tool is better able to satisfy the requiremtns of running
different tests differently even in a cross-build environment. It also supports
the ability to install or package the testsuite separately so it can be run on a
remote target.

Because of the increased flexibility of the GNU autotest tool, a number of test
runner scripts were no longer necessary and have been removed.

The github action was updated ot use thw new test tool instead of the
automake-generated one.

diff --git a/tests/run-coredump-unwind b/tests/run-coredump-unwind
--- a/tests/run-coredump-unwind
+++ b/tests/run-coredump-unwind
@@ -37,7 +37,14 @@ TESTDIR=`pwd`
 TEMPDIR=`mktemp --tmpdir -d libunwind-test-XXXXXXXXXX`
 trap "rm -r -- $TEMPDIR" EXIT
 
-cp crasher $TEMPDIR/crasher
+# `crasher` program must be found in $PATH
+CRASHER=$(which crasher)
+if [ -z "$CRASHER" ]; then
+    printf "error: can not find crasher program\n" >2
+    exit 1
+fi
+
+cp $CRASHER $TEMPDIR/crasher
 if [ "$1" = "-minidebuginfo" ]; then
   add_minidebug $TEMPDIR/crasher
 fi
@@ -51,4 +58,4 @@ fi
 COREFILE=$TEMPDIR/core*
 
 # magic option -testcase enables checking for the specific contents of the stack
-./test-coredump-unwind $COREFILE -testcase `cat $TEMPDIR/backing_files`
+test-coredump-unwind $COREFILE -testcase `cat $TEMPDIR/backing_files`
